baseURL = 'https://frahz.dev/'
languageCode = 'en-us'
title = 'frahz'
author = "frahz"
copyright = "© frahz"

theme = "archie"
pagination.pagerSize = 10

[markup]
[markup.highlight]
codeFences = true
guessSyntax = true
noClasses = false
style = "catppuccin-macchiato"

[params]
mode = "dark"
customcss = ["css/custom.css", "css/macchiato-chroma-style.css"]
katex = true
# set a custom favicon (default is a `themeColor` square)
favicon = "/images/favicon.ico"
toc = false

[[params.social]]
name = "GitHub"
icon = "simple:github"
url = "https://github.com/frahz"

[[params.social]]
name = "LinkedIn"
icon = "simple:linkedin"
url = "https://www.linkedin.com/in/abreuf/"

[[params.social]]
name = "Mastodon"
icon = "simple:mastodon"
url = "https://hachyderm.io/@frahz"

[[params.social]]
name = "Bluesky"
icon = "simple:bluesky"
url = "https://bsky.app/profile/frahz.dev"

[[params.social]]
name = "RSS"
icon = "simple:rss"
url = "https://frahz.dev/index.xml"

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "posts"
url = "/posts"
weight = 2

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 10
